# Generated by Django 5.1 on 2024-08-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_tag_scope_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
